alertmanager:
  persistentVolume:
    storageClass: "gp3"

server:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi

  configMaps:
    prometheus-yml: prometheus-cm
  ingress:
    enabled: true
    hosts:
      - aaef870036aac49368ad5580990dd1f3-1955026494.us-east-1.elb.amazonaws.com
    paths:
      - "/"
    annotations:
      kubernetes.io/ingress.class: "nginx"
