apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cm
  namespace: logging  # Change this to the namespace where you want to deploy Fluent Bit
data:
  fluent-bit.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Decode_Field_As   escaped    message
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^<remaining-regex-pattern>
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 50MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag log.systemd
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Buffer_Size 1Mb
        Merge_Log On
        Keep_Log Off
        Merge_Log_Key message
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name                    gelf
        Match                   log.systemd
        Host                    54.86.95.48
        Port                    12201
        Mode                    tcp
        Gelf_Short_Message_Key  MESSAGE
        Host_Key    non-prod-eks
        Retry_Limit 100
        tls off
    [OUTPUT]
        Name                    gelf
        Match                   kube.*
        Host                    54.86.95.48
        Port                    12202
        Mode                    tcp
        Gelf_Short_Message_Key  message
        Host_Key    non-prod-eks
        Retry_Limit 100
        tls off

