controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10254"
  readinessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
  livenessProbe:
    httpGet:
      path: "/healthz"
      port: 10254
